language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - PIP_ACCEL_S3_BUCKET=
  - PIP_ACCEL_S3_BUCKET=pip-accel-test-bucket
before_install:
  - sudo apt-get update
install:
  - pip install coveralls --editable "file://${PWD}[s3]"
  - sudo apt-get install --yes rubygems
  - sudo gem install fakes3
script:
  ./.travis.sh
after_success:
  coveralls
