sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - PIP_ACCEL_S3_BUCKET=
  - PIP_ACCEL_S3_BUCKET=pip-accel-test-bucket
before_install:
  - scripts/retry-command sudo apt-get update
install:
  - scripts/retry-command pip install coveralls --editable "file://${PWD}[s3]"
  - scripts/retry-command gem install fakes3
script:
  - scripts/collect-full-coverage
after_success:
  - scripts/retry-command coveralls
