language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install coveralls
  - python setup.py install
env:
  global:
    - PIP_ACCEL_TEST_AUTO_INSTALL=true
script:
  coverage run --source=pip_accel setup.py test
after_success:
  coveralls
