language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  global:
    - PIP_ACCEL_S3_CREATE_BUCKET=true
    - PIP_ACCEL_S3_URL="http://localhost:12345"
    - PIP_ACCEL_TEST_AUTO_INSTALL=true
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
  matrix:
    - PIP_ACCEL_S3_BUCKET=
    - PIP_ACCEL_S3_BUCKET=pip-accel-test-bucket
before_install:
  - sudo apt-get update
install:
  - pip install coveralls --editable "file://${PWD}[s3]"
  - sudo apt-get install --yes rubygems
  - sudo gem install fakes3
  - start-stop-daemon --start --quiet --pidfile /tmp/fakes3.pid --make-pidfile --background --exec /usr/local/bin/fakes3 -- --root=/tmp/fakes3 --port=12345
script:
  coverage run --source=pip_accel setup.py test
after_success:
  coveralls
