# appveyor.yml: Configuration for continuous integration (automated tests)
# hosted on AppVeyor, see https://ci.appveyor.com/project/xolox/pip-accel.
#
# This uses a forked coveralls-python until my pull request is merged:
# https://github.com/coagulant/coveralls-python/pull/97

version: 1.0.{build}
environment:
  PYTHON: C:\Python27
  COVERALLS_REPO_TOKEN:
    secure: DCxZQaYFWVR0zWqjTPXhhlRlLdmKNMS2qDUwIR8jRar13clunOqJIaXn+vKInS7g
install:
  - cmd: '"%PYTHON%\Scripts\pip.exe" install . https://github.com/xolox/coveralls-python/archive/master.zip'
  - cmd: 'scripts\collect-full-coverage.cmd'
build: off
test_script:
  - cmd: '"%PYTHON%\Scripts\coverage.exe" run setup.py test'
on_success:
  - cmd: '"%PYTHON%\Scripts\coveralls.exe"'
